; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Akilli Pano"
#define MyAppVersion "1.0"
#define MyAppPublisher "Sadullah"
#define MyAppExeName "AkilliPano.exe"
#define ProjectDir "."

[Setup]
; ...
AppId={{A1B2C3D4-E5F6-7890-1234-567890ABCDEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputBaseFilename=AkilliPano_Kurulum
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile={#ProjectDir}\logo.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"


[Files]
Source: "{#ProjectDir}\dist\AkilliPano\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ProjectDir}\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
; NOTE: .env is NOT included - user should configure it after install

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "AkilliPano"; Flags: uninsdeletevalue

[UninstallDelete]
; Remove autostart entries
Type: files; Name: "{userstartup}\AkilliPano.bat"
Type: files; Name: "{userstartup}\AkilliPano.lnk"

; Remove logs
Type: files; Name: "{app}\launcher.log"
Type: files; Name: "{app}\launcher.log.*"

; Remove data files (user generated)
Type: files; Name: "{app}\data\*.json"
Type: files; Name: "{app}\data\*"
Type: dirifempty; Name: "{app}\data"

; Remove uploaded/generated static content
Type: files; Name: "{app}\src\web\static\slideshow\*"
Type: dirifempty; Name: "{app}\src\web\static\slideshow"
Type: files; Name: "{app}\src\web\static\riddles\*"
Type: dirifempty; Name: "{app}\src\web\static\riddles"
Type: files; Name: "{app}\src\web\static\img\school_logo.*"

; Attempt to remove the application directory if empty (after improved cleanup)
; Attempt to remove the application directory and all contents (force cleanup)
Type: filesandordirs; Name: "{app}"
